<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            // Only categories with slider images - these will appear in the slider
            [
                'id' => 1,
                'name' => 'هدايا دعائية',
                'name_ar' => 'هدايا دعائية',
                'description' => 'نقدم لك مجموعة متنوعة من الهدايا الدعائية عالية الجودة، بتصاميم عصرية مخصصة تعزز حضورك وتبقي علامتك التجارية في ذاكرة عملائك',
                'description_ar' => 'نقدم لك مجموعة متنوعة من الهدايا الدعائية عالية الجودة، بتصاميم عصرية مخصصة تعزز حضورك وتبقي علامتك التجارية في ذاكرة عملائك',
                'image' => 'storage/categories/1758452372_WhatsApp Image 2025-09-04 at 8.53.29 AM.jpeg',
                'main_image' => 'storage/categories-main/أكياس.jpg',
                'slider_image' => 'storage/categories-slider/أكــيــاس.png',
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => '2025-09-19 21:25:13',
                'updated_at' => '2025-09-21 15:39:53',
            ],
            [
                'id' => 2,
                'name' => 'مطاعم ـ بيتزا ـ شاورما ـ كافيهات',
                'name_ar' => 'مطاعم ـ بيتزا ـ شاورما',
                'description' => 'حوّل منتجك إلى علامة مميزة مع تصاميم مبتكرة ومواد مطبوعة بجودة عالية – من قوائم الطعام إلى التغليف اجذب عملاءك بهوية بصرية تعكس نكهتك وتترك انطباعًا لا يُنسى',
                'description_ar' => 'حوّل منتجك إلى علامة مميزة مع تصاميم مبتكرة ومواد مطبوعة بجودة عالية – من قوائم الطعام إلى التغليف  اجذب عملاءك بهوية بصرية تعكس نكهتك وتترك انطباعًا لا يُنسى',
                'image' => 'storage/categories/1758453007_منتجات.png',
                'main_image' => 'storage/categories-main/المطاعم.jpg',
                'slider_image' => 'storage/categories-slider/المطاعم.png',
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => '2025-09-19 21:25:13',
                'updated_at' => '2025-09-21 15:47:08',
            ],
            [
                'id' => 12,
                'name' => 'مطاعم البرجر',
                'name_ar' => 'مطاعم البرجر',
                'description' => 'تصاميم مخصصة لمطاعم البرجر بأسلوب عصري يجذب العملاء',
                'description_ar' => 'تصاميم مخصصة لمطاعم البرجر بأسلوب عصري يجذب العملاء',
                'image' => null,
                'main_image' => 'storage/categories-main/برجر.jpg',
                'slider_image' => 'storage/categories-slider/مطاعـــم البرجــــر.png',
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'مطاعم بوفيات',
                'name_ar' => 'مطاعم بوفيات',
                'description' => 'حلول طباعة مخصصة لمطاعم البوفيات',
                'description_ar' => 'حلول طباعة مخصصة لمطاعم البوفيات',
                'image' => null,
                'main_image' => 'storage/categories-main/بوفيات 1.jpg',
                'slider_image' => 'storage/categories-slider/مطاعـــم بوفيـــات.png',
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'مطاعم بيتزا',
                'name_ar' => 'مطاعم بيتزا',
                'description' => 'تصاميم جذابة لمطاعم البيتزا',
                'description_ar' => 'تصاميم جذابة لمطاعم البيتزا',
                'image' => null,
                'main_image' => 'storage/categories-main/بيتزا 1.jpg',
                'slider_image' => 'storage/categories-slider/مطاعـــم بيــتــزا.png',
                'is_active' => true,
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'حلويات وشوكلاته',
                'name_ar' => 'حلويات وشوكلاته',
                'description' => 'تصاميم حلوة لمحلات الحلويات والشوكولاتة',
                'description_ar' => 'تصاميم حلوة لمحلات الحلويات والشوكولاتة',
                'image' => null,
                'main_image' => 'storage/categories-main/حلويات و شوكلاته.jpg',
                'slider_image' => 'storage/categories-slider/حلويات و شوكلاته.png',
                'is_active' => true,
                'sort_order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'عطور',
                'name_ar' => 'عطور',
                'description' => 'تصاميم أنيقة لمحلات العطور',
                'description_ar' => 'تصاميم أنيقة لمحلات العطور',
                'image' => null,
                'main_image' => 'storage/categories-main/عطور.jpg',
                'slider_image' => 'storage/categories-slider/عــطور.png',
                'is_active' => true,
                'sort_order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'مطاعم كافيات',
                'name_ar' => 'مطاعم كافيات',
                'description' => 'تصاميم مريحة لمقاهي ومطاعم الكافيات',
                'description_ar' => 'تصاميم مريحة لمقاهي ومطاعم الكافيات',
                'image' => null,
                'main_image' => 'storage/categories-main/كافيات 1.jpg',
                'slider_image' => 'storage/categories-slider/مطاعـــم كافيــات.png',
                'is_active' => true,
                'sort_order' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'مطاعم شاورما',
                'name_ar' => 'مطاعم شاورما',
                'description' => 'تصاميم شهية لمطاعم الشاورما',
                'description_ar' => 'تصاميم شهية لمطاعم الشاورما',
                'image' => null,
                'main_image' => 'storage/categories-main/شاورما.jpg',
                'slider_image' => 'storage/categories-slider/مطاعـــم شــاورمـــا.png',
                'is_active' => true,
                'sort_order' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Original categories that were missing
            [
                'id' => 7,
                'name' => 'Exhibition & Display',
                'name_ar' => 'معارض وعروض',
                'description' => 'Professional exhibition and display solutions for trade shows, events, and marketing campaigns.',
                'description_ar' => 'حلول احترافية للمعارض والعروض للمعارض التجارية والفعاليات والحملات التسويقية.',
                'image' => null,
                'main_image' => 'storage/categories-main/exhibition.jpg',
                'slider_image' => 'storage/categories-slider/exhibition.png',
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Perfume Boxes',
                'name_ar' => 'صناديق العطور',
                'description' => 'Elegant and luxurious perfume packaging boxes with custom designs.',
                'description_ar' => 'صناديق أنيقة وفاخرة لتغليف العطور بتصاميم مخصصة.',
                'image' => null,
                'main_image' => 'storage/categories-main/perfume-boxes.jpg',
                'slider_image' => 'storage/categories-slider/perfume-boxes.png',
                'is_active' => true,
                'sort_order' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Office & Business',
                'name_ar' => 'مكتبية وتجارية',
                'description' => 'Professional office and business printing solutions for corporate needs.',
                'description_ar' => 'حلول طباعة احترافية للمكاتب والأعمال التجارية للاحتياجات المؤسسية.',
                'image' => null,
                'main_image' => 'storage/categories-main/office-business.jpg',
                'slider_image' => 'storage/categories-slider/office-business.png',
                'is_active' => true,
                'sort_order' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Office Name Plates',
                'name_ar' => 'لوحات أسماء مكتبية',
                'description' => 'Professional name plates and signage for offices and businesses.',
                'description_ar' => 'لوحات أسماء ولافتات احترافية للمكاتب والأعمال التجارية.',
                'image' => null,
                'main_image' => 'storage/categories-main/name-plates.jpg',
                'slider_image' => 'storage/categories-slider/name-plates.png',
                'is_active' => true,
                'sort_order' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($categories as $category) {
            Category::updateOrCreate(
                ['id' => $category['id']],
                $category
            );
        }
    }
}