<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            [
                'id' => 1,
                'name' => 'هدايا دعائية',
                'name_ar' => 'هدايا دعائية',
                'description' => 'نقدم لك مجموعة متنوعة من الهدايا الدعائية عالية الجودة، بتصاميم عصرية مخصصة تعزز حضورك وتبقي علامتك التجارية في ذاكرة عملائك',
                'description_ar' => 'نقدم لك مجموعة متنوعة من الهدايا الدعائية عالية الجودة، بتصاميم عصرية مخصصة تعزز حضورك وتبقي علامتك التجارية في ذاكرة عملائك',
                'image' => 'storage/categories/1758452372_WhatsApp Image 2025-09-04 at 8.53.29 AM.jpeg',
                'main_image' => 'storage/categories-main/أكياس.jpg',
                'slider_image' => 'storage/categories-slider/أكــيــاس.png',
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => '2025-09-19 21:25:13',
                'updated_at' => '2025-09-21 15:39:53',
            ],
            [
                'id' => 2,
                'name' => 'مطاعم ـ بيتزا ـ شاورما ـ كافيهات',
                'name_ar' => 'مطاعم ـ بيتزا ـ شاورما',
                'description' => 'حوّل منتجك إلى علامة مميزة مع تصاميم مبتكرة ومواد مطبوعة بجودة عالية – من قوائم الطعام إلى التغليف اجذب عملاءك بهوية بصرية تعكس نكهتك وتترك انطباعًا لا يُنسى',
                'description_ar' => 'حوّل منتجك إلى علامة مميزة مع تصاميم مبتكرة ومواد مطبوعة بجودة عالية – من قوائم الطعام إلى التغليف  اجذب عملاءك بهوية بصرية تعكس نكهتك وتترك انطباعًا لا يُنسى',
                'image' => 'storage/categories/1758453007_منتجات.png',
                'main_image' => 'storage/categories-main/المطاعم.jpg',
                'slider_image' => 'storage/categories-slider/المطاعم.png',
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => '2025-09-19 21:25:13',
                'updated_at' => '2025-09-21 15:47:08',
            ],
            [
                'id' => 3,
                'name' => 'مناسبات الوطنية والعالمية في السعودية',
                'name_ar' => 'مناسبات الوطنية والعالمية في السعودية',
                'description' => 'احتفل بالمناسبات الوطنية والعالمية بلمسة إبداعية',
                'description_ar' => 'احتفل بالمناسبات الوطنية والعالمية بلمسة إبداعية',
                'image' => 'storage/categories/1758453499_مناسبات الوطنية والعالمية في السعودية.jpg',
                'main_image' => null,
                'slider_image' => null,
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => '2025-09-19 21:25:13',
                'updated_at' => '2025-09-21 15:44:41',
            ],
            [
                'id' => 4,
                'name' => 'القطاع الصحي',
                'name_ar' => 'القطاع الصحي',
                'description' => 'نقدم خدمات التصميم والطباعة بجودة عالية ومعايير احترافية، لتلبية احتياجات الجهات الحكومية في المطبوعات الرسمية، الهدايا التذكارية، والمواد التعريفية بأسلوب يعكس الهوية المؤسسية ويواكب التطور الرقمي',
                'description_ar' => 'نقدم خدمات التصميم والطباعة بجودة عالية ومعايير احترافية، لتلبية احتياجات الجهات الحكومية في المطبوعات الرسمية، الهدايا التذكارية، والمواد التعريفية بأسلوب يعكس الهوية المؤسسية ويواكب التطور الرقمي',
                'image' => null,
                'main_image' => null,
                'slider_image' => null,
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => '2025-09-19 21:25:14',
                'updated_at' => '2025-09-22 08:34:24',
            ],
            [
                'id' => 5,
                'name' => 'القطاع التعليمي',
                'name_ar' => 'القطاع التعليمي',
                'description' => 'اجعل كل مادة تعليمية وفعالية مدرسية تنبض بالإبداع والجودة."',
                'description_ar' => 'اجعل كل مادة تعليمية وفعالية مدرسية تنبض بالإبداع والجودة."',
                'image' => null,
                'main_image' => null,
                'slider_image' => null,
                'is_active' => true,
                'sort_order' => 5,
                'created_at' => '2025-09-19 21:25:14',
                'updated_at' => '2025-09-21 15:51:57',
            ],
            [
                'id' => 7,
                'name' => 'تنظيم المؤتمرات والفعاليات',
                'name_ar' => 'تنظيم المؤتمرات والفعاليات',
                'description' => 'نمنحك الحل الأمثل لتنظيم المؤتمرات والفعاليات باحترافية، من التخطيط وحتى التنفيذ',
                'description_ar' => 'نمنحك الحل الأمثل لتنظيم المؤتمرات والفعاليات باحترافية، من التخطيط وحتى التنفيذ',
                'image' => 'storage/categories/1758452251_بوث (1).jpg',
                'main_image' => 'storage/categories-main/تنظيم المواتمرات والفعاليات.jpg',
                'slider_image' => null,
                'is_active' => true,
                'sort_order' => 6,
                'created_at' => '2025-09-21 14:54:53',
                'updated_at' => '2025-09-21 15:34:26',
            ],
            [
                'id' => 8,
                'name' => 'المتاجر الالكترونية',
                'name_ar' => 'المتاجر الالكترونية',
                'description' => 'اجعل متجرك الإلكتروني يتألق بتصاميم وطباعة مبتكرة – قدّم لعملائك تجربة تسوق لا تُنسى',
                'description_ar' => 'اجعل متجرك الإلكتروني يتألق بتصاميم وطباعة مبتكرة – قدّم لعملائك تجربة تسوق لا تُنسى',
                'image' => null,
                'main_image' => null,
                'slider_image' => null,
                'is_active' => true,
                'sort_order' => 7,
                'created_at' => '2025-09-21 15:54:03',
                'updated_at' => '2025-09-22 08:36:30',
            ],
            [
                'id' => 9,
                'name' => 'دعاية واعلان',
                'name_ar' => 'دعاية واعلان',
                'description' => 'قدم حلول مبتكرة في التصميم والطباعة لتلبية احتياجات الجهات الحكومية والشركات الخاصة، بهوية متفردة وجودة عالية تعكس احترافية علامتك.',
                'description_ar' => 'قدم حلول مبتكرة في التصميم والطباعة لتلبية احتياجات الجهات الحكومية والشركات الخاصة، بهوية متفردة وجودة عالية تعكس احترافية علامتك.',
                'image' => null,
                'main_image' => null,
                'slider_image' => null,
                'is_active' => true,
                'sort_order' => 8,
                'created_at' => '2025-09-22 08:36:07',
                'updated_at' => '2025-09-22 14:26:34',
            ],
            [
                'id' => 10,
                'name' => 'منتجات خاصة',
                'name_ar' => 'منتجات خاصة',
                'description' => 'منصتنا الإلكترونية المتخصصة في التصميم والطباعة تقدم لك منتجات مخصصة بجودة عالية، تعكس هويتك وتمنحك تجربة استثنائية في إبراز علامتك بأسلوب مبتكر',
                'description_ar' => 'منصتنا الإلكترونية المتخصصة في التصميم والطباعة تقدم لك منتجات مخصصة بجودة عالية، تعكس هويتك وتمنحك تجربة استثنائية في إبراز علامتك بأسلوب مبتكر',
                'image' => null,
                'main_image' => null,
                'slider_image' => null,
                'is_active' => true,
                'sort_order' => 9,
                'created_at' => '2025-09-22 08:38:49',
                'updated_at' => '2025-09-22 09:08:45',
            ],
            [
                'id' => 11,
                'name' => 'اكريلك',
                'name_ar' => 'اكريلك',
                'description' => 'اكريلك',
                'description_ar' => 'اكريلك',
                'image' => null,
                'main_image' => null,
                'slider_image' => null,
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => '2025-09-22 14:29:52',
                'updated_at' => '2025-09-22 14:29:52',
            ],
            // Add specific restaurant categories with proper images
            [
                'id' => 12,
                'name' => 'مطاعم البرجر',
                'name_ar' => 'مطاعم البرجر',
                'description' => 'تصاميم مخصصة لمطاعم البرجر بأسلوب عصري يجذب العملاء',
                'description_ar' => 'تصاميم مخصصة لمطاعم البرجر بأسلوب عصري يجذب العملاء',
                'image' => null,
                'main_image' => 'storage/categories-main/برجر.jpg',
                'slider_image' => 'storage/categories-slider/مطاعـــم البرجــــر.png',
                'is_active' => true,
                'sort_order' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'مطاعم بوفيات',
                'name_ar' => 'مطاعم بوفيات',
                'description' => 'حلول طباعة مخصصة لمطاعم البوفيات',
                'description_ar' => 'حلول طباعة مخصصة لمطاعم البوفيات',
                'image' => null,
                'main_image' => 'storage/categories-main/بوفيات 1.jpg',
                'slider_image' => 'storage/categories-slider/مطاعـــم بوفيـــات.png',
                'is_active' => true,
                'sort_order' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'مطاعم بيتزا',
                'name_ar' => 'مطاعم بيتزا',
                'description' => 'تصاميم جذابة لمطاعم البيتزا',
                'description_ar' => 'تصاميم جذابة لمطاعم البيتزا',
                'image' => null,
                'main_image' => 'storage/categories-main/بيتزا 1.jpg',
                'slider_image' => 'storage/categories-slider/مطاعـــم بيــتــزا.png',
                'is_active' => true,
                'sort_order' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'حلويات وشوكلاته',
                'name_ar' => 'حلويات وشوكلاته',
                'description' => 'تصاميم حلوة لمحلات الحلويات والشوكولاتة',
                'description_ar' => 'تصاميم حلوة لمحلات الحلويات والشوكولاتة',
                'image' => null,
                'main_image' => 'storage/categories-main/حلويات و شوكلاته.jpg',
                'slider_image' => 'storage/categories-slider/حلويات و شوكلاته.png',
                'is_active' => true,
                'sort_order' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'عطور',
                'name_ar' => 'عطور',
                'description' => 'تصاميم أنيقة لمحلات العطور',
                'description_ar' => 'تصاميم أنيقة لمحلات العطور',
                'image' => null,
                'main_image' => 'storage/categories-main/عطور.jpg',
                'slider_image' => 'storage/categories-slider/عــطور.png',
                'is_active' => true,
                'sort_order' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'مطاعم كافيات',
                'name_ar' => 'مطاعم كافيات',
                'description' => 'تصاميم مريحة لمقاهي ومطاعم الكافيات',
                'description_ar' => 'تصاميم مريحة لمقاهي ومطاعم الكافيات',
                'image' => null,
                'main_image' => 'storage/categories-main/كافيات 1.jpg',
                'slider_image' => 'storage/categories-slider/مطاعـــم كافيــات.png',
                'is_active' => true,
                'sort_order' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'مطاعم شاورما',
                'name_ar' => 'مطاعم شاورما',
                'description' => 'تصاميم شهية لمطاعم الشاورما',
                'description_ar' => 'تصاميم شهية لمطاعم الشاورما',
                'image' => null,
                'main_image' => 'storage/categories-main/شاورما.jpg',
                'slider_image' => 'storage/categories-slider/مطاعـــم شــاورمـــا.png',
                'is_active' => true,
                'sort_order' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($categories as $category) {
            Category::updateOrCreate(
                ['id' => $category['id']],
                $category
            );
        }
    }
}
