<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\ProductOption;
use App\Models\OptionValue;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->createAllProducts();
    }

    private function createAllProducts()
    {
        // Category 1: Gifts/Promotional Items
        $this->createGiftProducts();
        
        // Category 2: Food Packaging
        $this->createFoodPackagingProducts();
        
        // Category 7: Exhibition & Display
        $this->createExhibitionProducts();
        
        // Category 8: Perfume Boxes
        $this->createPerfumeBoxProducts();
        
        // Category 9: Office & Business
        $this->createOfficeProducts();
        
        // Category 11: Office Name Plates
        $this->createOfficeNamePlateProducts();
    }

    private function createGiftProducts()
    {
        $giftProducts = [
            [
                'id' => 57,
                'category_id' => 1,
                'name' => 'Bag Printing',
                'name_ar' => 'طباعة على شنط',
                'description' => 'High-quality printing on various types of bags with vibrant colors and durable designs. Perfect for promotional gifts, conferences, events, or personal use.',
                'description_ar' => 'طباعة على الشنط: لتحويل الشنط إلى قطع فريدة تعكس هوية علامتك التجارية أو تصميمك الشخصي. نوفّر طباعة عالية الجودة على مختلف أنواع الشنط—بألوان زاهية وتصاميم مميزة تدوم طويلاً. مثالية للهدايا الترويجية، المؤتمرات، الفعاليات، أو الاستخدام الشخصي، لتجعل كل شنطة تعبيرًا حقيقيًا عن ذوقك أو شعار شركتك',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758524944_0_شنطة.jpg',
                'created_at' => '2025-09-22 11:09:04',
                'updated_at' => '2025-09-22 11:09:04',
            ],
            [
                'id' => 58,
                'category_id' => 1,
                'name' => 'Ceramic Mugs with Printing',
                'name_ar' => 'كاسات سيراميك مع الطباعة',
                'description' => 'Elegant and practical ceramic mugs for hot and cold beverages. Durable, easy to clean, with your custom design or company logo printing.',
                'description_ar' => 'كاسات سيراميك أنيقة وعملية، لتحمل المشروبات الساخنة والباردة، تتميز بمتانتها وسهولة تنظيفها، طباعة تصميمك الخاص او شعار شركتك تضيف لمسة جمالية لأي مناسبة أو استخدام يومي.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758525377_0_مج سيراميك.jpg',
                'created_at' => '2025-09-22 11:16:17',
                'updated_at' => '2025-09-22 11:16:17',
            ],
            [
                'id' => 59,
                'category_id' => 1,
                'name' => 'Steel Mugs',
                'name_ar' => 'مج ستيل',
                'description' => 'Durable and modern steel mugs, perfect for hot and cold beverages. Rust-resistant and easy to clean, with your custom design or company logo.',
                'description_ar' => 'مج ستيل متين وعصري، مثالي للمشروبات الساخنة والباردة، مقاوم للصدأ وسهل التنظيف، مع طباعة تصميمك الشخصي او شعار شركتك يجمع بين العملية والجمال للاستخدام اليومي أو كهدية مميزة.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758525838_0_مح اسيتل.jpg',
                'created_at' => '2025-09-22 11:23:58',
                'updated_at' => '2025-09-22 11:23:58',
            ],
            [
                'id' => 60,
                'category_id' => 1,
                'name' => 'Notebooks',
                'name_ar' => 'نوت بوك',
                'description' => 'Practical notebooks with custom design or company logo printing. Perfect for meetings, conferences, and daily use.',
                'description_ar' => 'نوت بوك عملي مع طباعة تصميمك الخاص أو شعار شركتك. مثالي للاجتماعات والمؤتمرات والاستخدام اليومي.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758526057_0_مفكرة.jpg',
                'created_at' => '2025-09-22 11:27:37',
                'updated_at' => '2025-09-22 11:27:37',
            ],
            [
                'id' => 61,
                'category_id' => 1,
                'name' => 'Medals',
                'name_ar' => 'ميداليات',
                'description' => 'Elegant medals with custom engraving. Perfect for awards, competitions, and recognition ceremonies.',
                'description_ar' => 'ميداليات أنيقة مع نقش مخصص. مثالية للجوائز والمسابقات ومراسم التكريم.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758526241_0_ميداليات.jpg',
                'created_at' => '2025-09-22 11:30:41',
                'updated_at' => '2025-09-22 11:30:41',
            ],
            [
                'id' => 62,
                'category_id' => 1,
                'name' => 'Pen Printing',
                'name_ar' => 'طباعة على الأقلام',
                'description' => 'High-quality pens with custom printing. Perfect for promotional gifts and corporate branding.',
                'description_ar' => 'أقلام عالية الجودة مع طباعة مخصصة. مثالية للهدايا الترويجية والعلامة التجارية للشركات.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758526313_0_قلك.png',
                'created_at' => '2025-09-22 11:31:53',
                'updated_at' => '2025-09-22 11:31:53',
            ],
            [
                'id' => 94,
                'category_id' => 1,
                'name' => 'Paper Bags',
                'name_ar' => 'اكياس',
                'description' => 'Eco-friendly paper bags with custom printing. Perfect for retail, events, and promotional use.',
                'description_ar' => 'الأكياس الورقية صديقة للبيئة مع طباعة مخصصة. مثالية للبيع بالتجزئة والفعاليات والاستخدام الترويجي.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758528261_0_كيس سندويات.jpg',
                'created_at' => '2025-09-22 11:44:21',
                'updated_at' => '2025-09-22 11:44:21',
            ],
        ];

        foreach ($giftProducts as $product) {
            Product::updateOrCreate(['id' => $product['id']], $product);
        }
    }

    private function createFoodPackagingProducts()
    {
        $foodProducts = [
            [
                'id' => 69,
                'category_id' => 2,
                'name' => 'Sandwich Bags',
                'name_ar' => 'كيس ساندويتش',
                'description' => 'Practical sandwich bags with custom printing. Perfect for food service, restaurants, and takeaway businesses.',
                'description_ar' => 'كيس ساندويش عملي مع طباعة مخصصة. مثالي لخدمات الطعام والمطاعم وأعمال التوصيل.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758528550_0_بوكسات شامورما العربي.jpg',
                'created_at' => '2025-09-22 11:49:10',
                'updated_at' => '2025-09-22 11:49:10',
            ],
            [
                'id' => 70,
                'category_id' => 2,
                'name' => 'Arabic Shawarma Box',
                'name_ar' => 'بوكس شاورما عربي',
                'description' => 'High-quality Arabic shawarma boxes with custom printing. Perfect for Middle Eastern food service.',
                'description_ar' => 'بوكس شاورما عربي عالي الجودة مع طباعة مخصصة. مثالي لخدمات الطعام الشرق أوسطي.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758528728_0_علبة بطاطس.jpg',
                'created_at' => '2025-09-22 11:52:08',
                'updated_at' => '2025-09-22 11:52:08',
            ],
            [
                'id' => 71,
                'category_id' => 2,
                'name' => 'French Fries Box',
                'name_ar' => 'علبة بطاطس',
                'description' => 'High-quality French fries boxes with custom printing. Perfect for fast food restaurants.',
                'description_ar' => 'علبة بطاطس عالية الجودة مع طباعة مخصصة. مثالية لمطاعم الوجبات السريعة.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758530190_0_ورق تغليف (1).png',
                'created_at' => '2025-09-22 12:03:10',
                'updated_at' => '2025-09-22 12:03:10',
            ],
            [
                'id' => 72,
                'category_id' => 2,
                'name' => 'Sandwich Wrapping Paper',
                'name_ar' => 'ورق تغليف ساندويتش',
                'description' => 'Practical sandwich wrapping paper with custom printing. Perfect for food service and restaurants.',
                'description_ar' => 'ورق تغليف ساندويتش عملي مع طباعة مخصصة. مثالي لخدمات الطعام والمطاعم.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758535698_0_أكياس تغليف القهوة.jpg',
                'created_at' => '2025-09-22 12:14:58',
                'updated_at' => '2025-09-22 12:14:58',
            ],
            [
                'id' => 73,
                'category_id' => 2,
                'name' => 'Coffee Packaging Bags',
                'name_ar' => 'اكياس تغليف القهوة',
                'description' => 'Elegant coffee packaging bags with custom printing. Perfect for coffee shops and roasters.',
                'description_ar' => 'أكياس قهوة أنيقة مع طباعة مخصصة. مثالية لمحلات القهوة والمحمصات.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758535783_0_كيس ورفي - كرافت.jpg',
                'created_at' => '2025-09-22 12:16:23',
                'updated_at' => '2025-09-22 12:16:23',
            ],
            [
                'id' => 74,
                'category_id' => 2,
                'name' => 'Kraft Paper Bags',
                'name_ar' => 'كيس ورقي كرافت',
                'description' => 'Eco-friendly kraft paper bags with custom printing. Perfect for retail and food service.',
                'description_ar' => 'كيس ورقي كرافت صديق للبيئة مع طباعة مخصصة. مثالي للبيع بالتجزئة وخدمات الطعام.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537517_0_بوكس بيتوا.jpg',
                'created_at' => '2025-09-22 12:31:57',
                'updated_at' => '2025-09-22 12:31:57',
            ],
            [
                'id' => 87,
                'category_id' => 2,
                'name' => 'Pizza Boxes',
                'name_ar' => 'بوكس بيتزا',
                'description' => 'Pizza boxes with custom printing. Perfect for pizzerias and delivery services.',
                'description_ar' => 'بوكسات البيتزا مع طباعة مخصصة. مثالية لمطاعم البيتزا وخدمات التوصيل.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537571_0_بوكس وجبات.jpg',
                'created_at' => '2025-09-22 12:32:51',
                'updated_at' => '2025-09-22 12:32:51',
            ],
            [
                'id' => 88,
                'category_id' => 2,
                'name' => 'Meal Boxes',
                'name_ar' => 'بوكس وجبات',
                'description' => 'Meal boxes with custom printing. Perfect for restaurants and food delivery services.',
                'description_ar' => 'بوكسات الوجبات مع طباعة مخصصة. مثالية للمطاعم وخدمات توصيل الطعام.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537648_0_صحن كرتون.jpg',
                'created_at' => '2025-09-22 12:34:08',
                'updated_at' => '2025-09-22 12:34:08',
            ],
            [
                'id' => 89,
                'category_id' => 2,
                'name' => 'Cardboard Plates',
                'name_ar' => 'صحن كرتوني',
                'description' => 'Cardboard plates with custom printing. Perfect for events and food service.',
                'description_ar' => 'الأطباق الكرتونية مع طباعة مخصصة. مثالية للفعاليات وخدمات الطعام.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537698_0_كوب بلاستيم.jpg',
                'created_at' => '2025-09-22 12:34:58',
                'updated_at' => '2025-09-22 12:34:58',
            ],
            [
                'id' => 90,
                'category_id' => 2,
                'name' => 'Plastic Cups',
                'name_ar' => 'كوب بلاستيك',
                'description' => 'Plastic cups with custom printing. Perfect for events and beverage service.',
                'description_ar' => 'الأكواب البلاستيكية مع طباعة مخصصة. مثالية للفعاليات وخدمات المشروبات.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537766_0_ميس طعام .jpg',
                'created_at' => '2025-09-22 12:36:06',
                'updated_at' => '2025-09-22 12:36:06',
            ],
            [
                'id' => 91,
                'category_id' => 2,
                'name' => 'Food Bags',
                'name_ar' => 'كيس طعام',
                'description' => 'Food bags with custom printing. Perfect for food service and takeaway.',
                'description_ar' => 'أكياس الطعام مع طباعة مخصصة. مثالية لخدمات الطعام والتوصيل.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537824_0_كيس --.jpg',
                'created_at' => '2025-09-22 12:37:04',
                'updated_at' => '2025-09-22 12:37:04',
            ],
            [
                'id' => 92,
                'category_id' => 2,
                'name' => 'Paper Bags',
                'name_ar' => 'اكياس ورقية',
                'description' => 'Paper bags with custom printing. Perfect for retail and food service.',
                'description_ar' => 'الأكياس الورقية مع طباعة مخصصة. مثالية للبيع بالتجزئة وخدمات الطعام.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537885_0_كيس ---.jpg',
                'created_at' => '2025-09-22 12:38:05',
                'updated_at' => '2025-09-22 12:38:05',
            ],
            [
                'id' => 97,
                'category_id' => 2,
                'name' => 'Paper Cup Holder',
                'name_ar' => 'حامل اكواب ورقي',
                'description' => 'Practical paper cup holder with custom printing. Perfect for beverage service.',
                'description_ar' => 'منتج عملي مع طباعة مخصصة. مثالي لخدمات المشروبات.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537969_0_كيس قماش - تاك .jpg',
                'created_at' => '2025-09-22 12:39:29',
                'updated_at' => '2025-09-22 12:39:29',
            ],
            [
                'id' => 99,
                'category_id' => 2,
                'name' => 'Kunafa Box',
                'name_ar' => 'بوكس كنافة',
                'description' => 'Special kunafa box with custom printing. Perfect for Middle Eastern desserts.',
                'description_ar' => 'علبة مميزة للكنافة مع طباعة مخصصة. مثالية للحلويات الشرق أوسطية.',
                'base_price' => 0.00,
            'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537974_0_كيس قماش - تاك .jpg',
                'created_at' => '2025-09-22 12:39:34',
                'updated_at' => '2025-09-22 12:39:34',
            ],
            [
                'id' => 100,
                'category_id' => 2,
                'name' => 'Single Pizza Box',
                'name_ar' => 'بوكس بيتزا ( قطعة واحدة )',
                'description' => 'Single pizza box with custom printing. Perfect for individual pizza orders.',
                'description_ar' => 'علبة عملية للبيتزا الفردية مع طباعة مخصصة. مثالية لطلبات البيتزا الفردية.',
                'base_price' => 0.00,
            'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537912_0_كيس - .jpg',
                'created_at' => '2025-09-22 12:38:32',
                'updated_at' => '2025-09-22 12:38:32',
            ],
            [
                'id' => 101,
                'category_id' => 2,
                'name' => 'Cup Holder',
                'name_ar' => 'حامل كوب',
                'description' => 'Cup holder used to secure cups during transport. Perfect for beverage delivery.',
                'description_ar' => 'يُستخدم لتثبيت الأكواب أثناء النقل. مثالي لتوصيل المشروبات.',
                'base_price' => 0.00,
            'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537912_1_كيس.jpg',
                'created_at' => '2025-09-22 12:38:32',
                'updated_at' => '2025-09-22 12:38:32',
            ],
            [
                'id' => 108,
                'category_id' => 2,
                'name' => 'Paper French Fries Bag',
                'name_ar' => 'كيس بطاطس ورقي',
                'description' => 'Present your French fries in an elegant paper bag with custom printing.',
                'description_ar' => 'قدّم بطاطسك في كيس ورقي أنيق مع طباعة مخصصة.',
                'base_price' => 0.00,
            'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537959_0_مكعبات فوركس.png',
                'created_at' => '2025-09-22 12:39:19',
                'updated_at' => '2025-09-22 12:39:19',
            ],
            [
                'id' => 109,
                'category_id' => 2,
                'name' => 'Sandwich Paper Bag',
                'name_ar' => 'كيس ورقي سندويشات',
                'description' => 'Paper bag designed for sandwich packaging with custom printing.',
                'description_ar' => 'كيس مخصص لتعبئة السندويشات مع طباعة مخصصة.',
                'base_price' => 0.00,
            'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537959_0_مكعبات فوركس.png',
                'created_at' => '2025-09-22 12:39:19',
                'updated_at' => '2025-09-22 12:39:19',
            ],
        ];

        foreach ($foodProducts as $product) {
            Product::updateOrCreate(['id' => $product['id']], $product);
        }
    }


    private function createExhibitionProducts()
    {
        $exhibitionProducts = [
            [
                'id' => 40,
                'category_id' => 7,
                'name' => 'Exhibition Booth',
                'name_ar' => 'بوث معارض',
                'description' => 'Design, print, and install exhibition booths. Perfect for trade shows, exhibitions, and corporate events.',
                'description_ar' => 'تصميم وطباعة تركيب بوثات المعارض',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758452511_0_بوث.jpg',
                'created_at' => '2025-09-21 15:01:50',
                'updated_at' => '2025-09-21 15:01:50',
            ],
            [
                'id' => 41,
                'category_id' => 7,
                'name' => 'Promotional Table',
                'name_ar' => 'طاولة دعائية',
                'description' => 'Promotional table perfect for displaying products and services at exhibitions and marketing events.',
                'description_ar' => 'طاولة دعائية يمكن وضع الشعار والأسم علهيا بشكل جذاب وأيضاً مثالية لعرض المنتجات والخدمات بجودة عالية وتصميم جذاب.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758453822_0_طاولة--.jpg',
                'created_at' => '2025-09-21 15:22:49',
                'updated_at' => '2025-09-22 08:43:07',
            ],
            [
                'id' => 45,
                'category_id' => 7,
                'name' => 'Banner Display',
                'name_ar' => 'لوحة بنر',
                'description' => 'High-quality banner displays for advertising and promotional purposes.',
                'description_ar' => 'لوحة بنر',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758518421_0_بنر.png',
                'created_at' => '2025-09-22 09:20:21',
                'updated_at' => '2025-09-22 09:20:21',
            ],
            [
                'id' => 46,
                'category_id' => 7,
                'name' => 'Pop-up Display',
                'name_ar' => 'بوب اب',
                'description' => 'Portable pop-up displays for exhibitions and events.',
                'description_ar' => 'بوب اب',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758518679_0_بوب اب.png',
                'created_at' => '2025-09-22 09:24:39',
                'updated_at' => '2025-09-22 09:24:39',
            ],
            [
                'id' => 47,
                'category_id' => 7,
                'name' => 'Roll-up Display',
                'name_ar' => 'رول اب',
                'description' => 'Roll-up displays in various sizes for exhibitions and events.',
                'description_ar' => 'رول اب',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758519504_0_رول اب.png',
                'created_at' => '2025-09-22 09:38:24',
                'updated_at' => '2025-09-22 09:38:24',
            ],
            [
                'id' => 49,
                'category_id' => 7,
                'name' => 'Name Badge',
                'name_ar' => 'بروش اسم',
                'description' => 'Custom name badges in various shapes and sizes according to your design.',
                'description_ar' => 'بروش اسم',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758519638_0_بروش اســم.png',
                'created_at' => '2025-09-22 09:40:42',
                'updated_at' => '2025-09-22 09:40:42',
            ],
            [
                'id' => 50,
                'category_id' => 7,
                'name' => 'T-Shirts',
                'name_ar' => 'تشيرتات',
                'description' => 'Design and printing on t-shirts of various types.',
                'description_ar' => 'تيشرتات',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758519793_0_تيشترتات.jpg',
                'created_at' => '2025-09-22 09:43:13',
                'updated_at' => '2025-09-22 09:43:13',
            ],
            [
                'id' => 51,
                'category_id' => 7,
                'name' => 'Caps',
                'name_ar' => 'كابات',
                'description' => 'Printing on caps using various techniques.',
                'description_ar' => 'كابات',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758520853_0_كابات.png',
                'created_at' => '2025-09-22 10:00:53',
                'updated_at' => '2025-09-22 10:00:53',
            ],
            [
                'id' => 52,
                'category_id' => 7,
                'name' => 'ID Cards',
                'name_ar' => 'بطاقات تعريفية ( عادي ـ ID )',
                'description' => 'Standard and ID cards for identification purposes.',
                'description_ar' => 'بطاقات تعريفية ( عادي ـ ID )',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758521690_0_بطائق اي دي.png',
                'created_at' => '2025-09-22 10:14:50',
                'updated_at' => '2025-09-22 10:14:50',
            ],
            [
                'id' => 53,
                'category_id' => 7,
                'name' => 'Promotional Table with Canopy',
                'name_ar' => 'طاولة دعائية مع مضلة',
                'description' => 'Pop-up table with canopy - a practical and elegant option for displaying your products and services at exhibitions and events.',
                'description_ar' => 'طاولة دعائية مع مضلة',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758522227_0_طاولة دعائية مع مظلة .png',
                'created_at' => '2025-09-22 10:23:47',
                'updated_at' => '2025-09-22 10:23:47',
            ],
            [
                'id' => 54,
                'category_id' => 7,
                'name' => 'Folding Table',
                'name_ar' => 'طاولة قابلة للطي',
                'description' => 'Folding table - a practical and elegant solution for displaying products and services on various occasions.',
                'description_ar' => 'طاولة قابلة للطي',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758522487_0_طاولة قـــابلـــة للطـــي .png',
                'created_at' => '2025-09-22 10:28:07',
                'updated_at' => '2025-09-22 10:28:07',
            ],
            [
                'id' => 55,
                'category_id' => 7,
                'name' => 'Curved Promotional Table',
                'name_ar' => 'طاولة دعائية مقوسة',
                'description' => 'Curved promotional table - perfect for presenting and displaying products and services professionally and attractively.',
                'description_ar' => 'طاولة دعائية مقوسة',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758522795_0_طاولة دعائية مقوسة .png',
                'created_at' => '2025-09-22 10:33:15',
                'updated_at' => '2025-09-22 10:33:15',
            ],
            [
                'id' => 56,
                'category_id' => 7,
                'name' => 'Backdrop Stand',
                'name_ar' => 'استاند باك دروب',
                'description' => 'Backdrop is a large background panel used in events, exhibitions, and conferences to highlight company logos, products, or marketing messages.',
                'description_ar' => 'استاند باك دروب',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758523555_0_باك دورب.png',
                'created_at' => '2025-09-22 10:45:55',
                'updated_at' => '2025-09-22 10:45:55',
            ],
            [
                'id' => 63,
                'category_id' => 7,
                'name' => 'Feather Flag',
                'name_ar' => 'علم الريشة',
                'description' => 'Lightweight feather flag perfect for outdoor advertising and events.',
                'description_ar' => 'علم الريشة خفيف مثالي للإعلان الخارجي والفعاليات.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758526569_0_علم الريشة.png',
                'created_at' => '2025-09-22 11:42:49',
                'updated_at' => '2025-09-22 11:42:49',
            ],
            [
                'id' => 64,
                'category_id' => 7,
                'name' => 'Teardrop Flag',
                'name_ar' => 'علم قطرة المطر',
                'description' => 'Teardrop-shaped flag perfect for outdoor advertising and events.',
                'description_ar' => 'علم على شكل قطرة المطر مثالي للإعلان الخارجي والفعاليات.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758526653_0_علم قطرة المطر.png',
                'created_at' => '2025-09-22 11:44:13',
                'updated_at' => '2025-09-22 11:44:13',
            ],
            [
                'id' => 65,
                'category_id' => 7,
                'name' => 'Rectangle Flag',
                'name_ar' => 'علم مستطيل',
                'description' => 'Durable rectangle flag perfect for outdoor advertising and events.',
                'description_ar' => 'علم مستطيل متين مثالي للإعلان الخارجي والفعاليات.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758526710_0_علم مستطيل.png',
                'created_at' => '2025-09-22 11:45:10',
                'updated_at' => '2025-09-22 11:45:10',
            ],
            [
                'id' => 66,
                'category_id' => 7,
                'name' => 'Telescope Flag',
                'name_ar' => 'علم تسلكوب',
                'description' => 'Practical telescope flag perfect for outdoor advertising and events.',
                'description_ar' => 'علم تلسكوب عملي مثالي للإعلان الخارجي والفعاليات.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758526978_0_علم تلسكوب.png',
                'created_at' => '2025-09-22 11:49:38',
                'updated_at' => '2025-09-22 11:49:38',
            ],
            [
                'id' => 68,
                'category_id' => 7,
                'name' => 'Foam Cubes',
                'name_ar' => 'مكعبات فوركس',
                'description' => 'Lightweight foam cubes perfect for exhibitions and displays.',
                'description_ar' => 'مكعبات الفوركس خفيفة مثالية للمعارض والعروض.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758527959_0_مكعبات فوركس.png',
                'created_at' => '2025-09-22 12:12:39',
                'updated_at' => '2025-09-22 12:12:39',
            ],
            [
                'id' => 77,
                'category_id' => 7,
                'name' => 'Foam Stands',
                'name_ar' => 'استاندات فوركس',
                'description' => 'Promotional foam stands perfect for exhibitions and displays.',
                'description_ar' => 'استاندات فوركس دعائية مثالية للمعارض والعروض.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758536005_0_استانــدات فوركس.jpg',
                'created_at' => '2025-09-22 12:20:05',
                'updated_at' => '2025-09-22 12:20:05',
            ],
        ];

        foreach ($exhibitionProducts as $product) {
            Product::updateOrCreate(['id' => $product['id']], $product);
        }
    }

    private function createPerfumeBoxProducts()
    {
        $perfumeProducts = [
            [
                'id' => 104,
                'category_id' => 8,
                'name' => 'Luxury Perfume Box',
                'name_ar' => 'بوكس فاخر للعطور',
                'description' => 'Elegant luxury perfume box with custom design.',
                'description_ar' => 'علبة أنيقة فاخرة للعطور مع تصميم مخصص.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537517_0_بوكس بيتوا.jpg',
                'created_at' => '2025-09-22 12:31:57',
                'updated_at' => '2025-09-22 12:31:57',
            ],
            [
                'id' => 105,
                'category_id' => 8,
                'name' => 'Perfume Box',
                'name_ar' => 'بوكس عطور',
                'description' => 'Elegant perfume box with custom design.',
                'description_ar' => 'علبة أنيقة للعطور مع تصميم مخصص.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537571_0_بوكس وجبات.jpg',
                'created_at' => '2025-09-22 12:32:51',
                'updated_at' => '2025-09-22 12:32:51',
            ],
        ];

        foreach ($perfumeProducts as $product) {
            Product::updateOrCreate(['id' => $product['id']], $product);
        }
    }

    private function createOfficeProducts()
    {
        $officeProducts = [
            [
                'id' => 75,
                'category_id' => 9,
                'name' => 'Car Stickers',
                'name_ar' => 'ستيكرات سيارات',
                'description' => 'High-quality car stickers with custom design.',
                'description_ar' => 'ستيكرات سيارات عالية الجودة مع تصميم مخصص.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758535945_0_سيكرات سيارات (1).jpg',
                'created_at' => '2025-09-22 12:19:05',
                'updated_at' => '2025-09-22 12:19:05',
            ],
            [
                'id' => 76,
                'category_id' => 9,
                'name' => 'Car Stickers',
                'name_ar' => 'ستيكرات سيارات',
                'description' => 'High-quality car stickers with custom design.',
                'description_ar' => 'ستيكرات سيارات عالية الجودة مع تصميم مخصص.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758535946_0_سيكرات سيارات (1).jpg',
                'created_at' => '2025-09-22 12:19:06',
                'updated_at' => '2025-09-22 12:19:06',
            ],
            [
                'id' => 78,
                'category_id' => 9,
                'name' => 'Metal Badge',
                'name_ar' => 'بروش معدن',
                'description' => 'Luxury metal badge with custom engraving.',
                'description_ar' => 'بروش معدني فاخر مع نقش مخصص.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758536065_0_بروش معدن.jpg',
                'created_at' => '2025-09-22 12:21:05',
                'updated_at' => '2025-09-22 12:21:05',
            ],
            [
                'id' => 79,
                'category_id' => 9,
                'name' => 'Stamps',
                'name_ar' => 'اختام',
                'description' => 'Practical stamps with custom design.',
                'description_ar' => 'أختام عملية مع تصميم مخصص.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758536139_0_ختم فادس.ai.png',
                'created_at' => '2025-09-22 12:22:19',
                'updated_at' => '2025-09-22 12:22:19',
            ],
            [
                'id' => 80,
                'category_id' => 9,
                'name' => 'Receipts (Payment & Receipt)',
                'name_ar' => 'سندات ( صرف ـ قبض )',
                'description' => 'Payment and receipt vouchers with custom design.',
                'description_ar' => 'سندات قبض وصرف مع تصميم مخصص.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758536214_0_سندات.jpg',
                'created_at' => '2025-09-22 12:23:34',
                'updated_at' => '2025-09-22 12:23:34',
            ],
            [
                'id' => 81,
                'category_id' => 9,
                'name' => 'Envelopes',
                'name_ar' => 'ظروف',
                'description' => 'Elegant paper envelopes with custom design.',
                'description_ar' => 'ظروف ورقية أنيقة مع تصميم مخصص.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758536315_0_ظروف.jpg',
                'created_at' => '2025-09-22 12:25:15',
                'updated_at' => '2025-09-22 12:25:15',
            ],
            [
                'id' => 82,
                'category_id' => 9,
                'name' => 'Invoices',
                'name_ar' => 'فواتير',
                'description' => 'Printed invoices with custom design.',
                'description_ar' => 'فواتير مطبوعة مع تصميم مخصص.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758536385_0_فواتير.jpg',
                'created_at' => '2025-09-22 12:26:25',
                'updated_at' => '2025-09-22 12:26:25',
            ],
            [
                'id' => 83,
                'category_id' => 9,
                'name' => 'Folders',
                'name_ar' => 'فولدرات',
                'description' => 'Folders with custom design.',
                'description_ar' => 'الفولدرات بتصميم مخصص.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758536516_0_قلوردات.jpg',
                'created_at' => '2025-09-22 12:28:36',
                'updated_at' => '2025-09-22 12:28:36',
            ],
            [
                'id' => 84,
                'category_id' => 9,
                'name' => 'Coupons',
                'name_ar' => 'كوبونات',
                'description' => 'Coupons with custom design.',
                'description_ar' => 'الكوبونات بتصميم مخصص.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758536634_0_كوبونات.jpg',
                'created_at' => '2025-09-22 12:30:34',
                'updated_at' => '2025-09-22 12:30:34',
            ],
            [
                'id' => 85,
                'category_id' => 9,
                'name' => 'Magazines',
                'name_ar' => 'مجلات',
                'description' => 'Magazines with custom design.',
                'description_ar' => 'المجلات بتصميم مخصص.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758536716_0_مجلات.jpg',
                'created_at' => '2025-09-22 12:31:56',
                'updated_at' => '2025-09-22 12:31:56',
            ],
            [
                'id' => 86,
                'category_id' => 9,
                'name' => 'Booklets',
                'name_ar' => 'كتيبات',
                'description' => 'Booklets with custom design.',
                'description_ar' => 'الكتيبات بتصميم مخصص.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537133_0_الكتيبات.jpg',
                'created_at' => '2025-09-22 12:38:53',
                'updated_at' => '2025-09-22 12:38:53',
            ],
            [
                'id' => 93,
                'category_id' => 9,
                'name' => 'Paper Bags',
                'name_ar' => 'اكياس ورقية',
                'description' => 'Paper bags with custom design.',
                'description_ar' => 'الأكياس الورقية مع تصميم مخصص.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537885_0_كيس ---.jpg',
                'created_at' => '2025-09-22 12:38:05',
                'updated_at' => '2025-09-22 12:38:05',
            ],
            [
                'id' => 95,
                'category_id' => 9,
                'name' => 'Tat Bag',
                'name_ar' => 'تات باق',
                'description' => 'Tat Bag (Tat Bag) with custom design.',
                'description_ar' => 'التات باق (Tat Bag) مع تصميم مخصص.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537912_0_كيس - .jpg',
                'created_at' => '2025-09-22 12:38:32',
                'updated_at' => '2025-09-22 12:38:32',
            ],
            [
                'id' => 98,
                'category_id' => 9,
                'name' => 'Stickers with Die Cut',
                'name_ar' => 'ستيكر مع قص داي كات',
                'description' => 'Innovative stickers with die cut design.',
                'description_ar' => 'ملصقات مبتكرة مع قص داي كات.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537912_1_كيس.jpg',
                'created_at' => '2025-09-22 12:38:32',
                'updated_at' => '2025-09-22 12:38:32',
            ],
            [
                'id' => 103,
                'category_id' => 9,
                'name' => 'Stickers with Plotter Cut',
                'name_ar' => 'ستيكرات مع قص بلوتر',
                'description' => 'High-quality stickers with plotter cut design.',
                'description_ar' => 'ملصقات عالية الجودة مع قص بلوتر.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537959_0_مكعبات فوركس.png',
                'created_at' => '2025-09-22 12:39:19',
                'updated_at' => '2025-09-22 12:39:19',
            ],
            [
                'id' => 106,
                'category_id' => 9,
                'name' => 'Sticker Sheet',
                'name_ar' => 'استيكر شيت',
                'description' => 'Design and print sticker sheets with custom design.',
                'description_ar' => 'تصميم وطباعة ستيكر شيت مع تصميم مخصص.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537959_0_مكعبات فوركس.png',
                'created_at' => '2025-09-22 12:39:19',
                'updated_at' => '2025-09-22 12:39:19',
            ],
            [
                'id' => 107,
                'category_id' => 9,
                'name' => 'Letterhead Paper',
                'name_ar' => 'ورق خطابات',
                'description' => 'Make your correspondence more professional with custom letterhead paper.',
                'description_ar' => 'اجعل مراسلاتك أكثر احترافية مع ورق خطابات مخصص.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537959_0_مكعبات فوركس.png',
                'created_at' => '2025-09-22 12:39:19',
                'updated_at' => '2025-09-22 12:39:19',
            ],
            [
                'id' => 110,
                'category_id' => 9,
                'name' => 'Calendar',
                'name_ar' => 'تقويم',
                'description' => 'Calendar is an essential tool for organizing time and tracking important dates.',
                'description_ar' => 'التقويم يعد أداة أساسية لتنظيم الوقت وتتبع التواريخ المهمة.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537959_0_مكعبات فوركس.png',
                'created_at' => '2025-09-22 12:39:19',
                'updated_at' => '2025-09-22 12:39:19',
            ],
        ];

        foreach ($officeProducts as $product) {
            Product::updateOrCreate(['id' => $product['id']], $product);
        }
    }

    private function createOfficeNamePlateProducts()
    {
        $namePlateProducts = [
            [
                'id' => 102,
                'category_id' => 11,
                'name' => 'Office Name Plate',
                'name_ar' => 'لوحة اسم مكتبية',
                'description' => 'Professional touch for your office with custom name plates.',
                'description_ar' => 'لمسة احترافية لمكتبك مع لوحات أسماء مخصصة.',
                'base_price' => 0.00,
                'is_active' => true,
                'sort_order' => 0,
                'specifications' => null,
                'image_url' => 'uploads/products/1758537959_0_مكعبات فوركس.png',
                'created_at' => '2025-09-22 12:39:19',
                'updated_at' => '2025-09-22 12:39:19',
            ],
        ];

        foreach ($namePlateProducts as $product) {
            Product::updateOrCreate(['id' => $product['id']], $product);
        }
    }

}
