<?php

use Livewire\Livewire;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

// Import middleware classes directly
use App\Http\Controllers\HomeController;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;
use Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect;
use Mcamara\LaravelLocalization\Middleware\LaravelLocalizationViewPath;
use Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter;

// User routes (generated by laravel/ui)

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [
            LocaleSessionRedirect::class,
            LaravelLocalizationRedirectFilter::class,
            LaravelLocalizationViewPath::class
        ]
    ],
    function () {

        // this solve conflict between livewire 3 and mcamara localization
        Livewire::setUpdateRoute(function ($handle) {
            return Route::post('/livewire/update', $handle);
        });

        Auth::routes();

        Route::redirect('/', '/home');
        Route::get('/home', [HomeController::class, 'index'])->name('home');
        // Route::view('/success', "admin.auth.success");

        require __DIR__ . '/admin_routes.php';
    }
);
